Description: >
    This template is design to deploy EC2 instance in AWS environment.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VpcId:
    Description: VPC Id for resources
    Default: AWS::SSM::Parameter::Value<AWS::EC2::VPC>
    #Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC>
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable access to the instance 
    Default: String
    Type: AWS::SSM::Parameter::Value<AWS::EC2::KeyPair::KeyName>
#    ConstrainDescription: Must be the name of an existing Ec2 KeyPair
  InstanceType: 
    Description: App EC2 instance type
    Type: String #AWS::SSM::Parameter::Value<String>
  SubnetID: 
    Description: App EC2 instance type
    Type: String #AWS::SSM::Parameter::Value<AWS::EC2::Subnet>
  ImageID: 
    Description: App EC2 instance type
    Type: String #AWS::SSM::Parameter::Value<AWS::EC2::Image::ID>
  
Resources:
  EC2Instance1:
    Type: AWS::EC2:Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      DisableApiTermination: true
      ImageId: 
        Ref: ImageID
      SubnetId: 
        Ref: SubnetID
      SecurityGroupIds:
        - sg-099b9caf0073e0a4e
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50

      Tags:
        - Key: Name
          Value: test58
        - Key: Product
          Value: test
        - Key: Type
          Value: Appserver
      
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            yum install httpd -y
            service httpd start
            echo "<html><body><h1>Hello from Region ${AWS::Region}<h1></body></html>" > /var/www/html/index.html
            
Outputs:
    PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]

        
